"""
AI Translation Agent — FastAPI Backend

Provides endpoints for:
  - /translate  — Text translation via Groq LLM
  - /transcribe — Audio-to-text via Groq Whisper
  - /summarize  — Translate + summarize transcriptions + email result

Includes in-memory caching and simple rate limiting.
"""

import base64
import hashlib
import io
import smtplib
import time
import tempfile
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from groq import Groq
from dotenv import load_dotenv
import os

# ── Load environment variables ────────────────────────────────────
load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
if not GROQ_API_KEY:
    raise RuntimeError(
        "GROQ_API_KEY not found. Create a .env file with:\n"
        "GROQ_API_KEY=your_key_here"
    )

# Email config (optional — summarize will still work without it)
SMTP_EMAIL    = os.getenv("SMTP_EMAIL", "")
SMTP_PASSWORD = os.getenv("SMTP_PASSWORD", "")
SMTP_SERVER   = os.getenv("SMTP_SERVER", "smtp.gmail.com")
SMTP_PORT     = int(os.getenv("SMTP_PORT", "587"))

# ── Groq client ───────────────────────────────────────────────────
client = Groq(api_key=GROQ_API_KEY)
MODEL = "llama-3.3-70b-versatile"
WHISPER_MODEL = "whisper-large-v3"

# ── FastAPI app setup ─────────────────────────────────────────────
app = FastAPI(
    title="AI Translation Agent",
    description="Backend translation + transcription + summarization service powered by Groq.",
    version="2.0.0",
)

# CORS — allow requests from any Chrome extension origin
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["POST", "GET", "OPTIONS"],
    allow_headers=["*"],
)

# ── In-memory translation cache ──────────────────────────────────
translation_cache: dict[str, str] = {}

# ── Simple rate limiter (1 request per second) ────────────────────
last_request_time: float = 0.0
RATE_LIMIT_SECONDS: float = 1.0

# ── Request / Response models ─────────────────────────────────────

class TranslationRequest(BaseModel):
    text: str

class TranslationResponse(BaseModel):
    translation: str

class TranscribeRequest(BaseModel):
    audio_data: str   # base64-encoded audio
    mime_type: str     # e.g. "audio/webm;codecs=opus"

class TranscribeResponse(BaseModel):
    text: str

class SummarizeRequest(BaseModel):
    transcriptions: list[str]
    email: str

class SummarizeResponse(BaseModel):
    summary: str
    email_sent: bool

# ── Helpers ───────────────────────────────────────────────────────

def _cache_key(text: str) -> str:
    """Generate a cache key from the input text."""
    return hashlib.sha256(text.strip().encode("utf-8")).hexdigest()


def _enforce_rate_limit():
    """Block if the last request was less than RATE_LIMIT_SECONDS ago."""
    global last_request_time
    now = time.time()
    elapsed = now - last_request_time
    if elapsed < RATE_LIMIT_SECONDS:
        time.sleep(RATE_LIMIT_SECONDS - elapsed)
    last_request_time = time.time()


def _send_email(to_email: str, subject: str, body: str) -> bool:
    """Send an email via SMTP. Returns True on success."""
    if not SMTP_EMAIL or not SMTP_PASSWORD:
        print("[Email] SMTP credentials not configured, skipping email.")
        return False

    try:
        msg = MIMEMultipart("alternative")
        msg["From"] = SMTP_EMAIL
        msg["To"] = to_email
        msg["Subject"] = subject

        # Plain text version
        msg.attach(MIMEText(body, "plain"))

        # HTML version
        html_body = f"""
        <html>
        <body style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto;">
            <div style="background: linear-gradient(135deg, #1e293b, #0f172a); padding: 24px; border-radius: 12px;">
                <h2 style="color: #6b8cff; margin-top: 0;">🌐 AI Translation Agent — Video Summary</h2>
                <div style="background: #1e293b; border-left: 4px solid #4a6cf7; padding: 16px; border-radius: 8px; color: #e2e8f0; line-height: 1.7;">
                    {body.replace(chr(10), '<br>')}
                </div>
                <p style="color: #64748b; font-size: 12px; margin-top: 16px;">
                    Generated by AI Translation Agent • Powered by Groq
                </p>
            </div>
        </body>
        </html>
        """
        msg.attach(MIMEText(html_body, "html"))

        with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as server:
            server.ehlo()
            server.starttls()
            server.ehlo()
            server.login(SMTP_EMAIL, SMTP_PASSWORD)
            server.send_message(msg)

        print(f"[Email] Summary sent to {to_email}")
        return True

    except Exception as exc:
        print(f"[Email] Failed to send: {exc}")
        return False


# ── Endpoints ─────────────────────────────────────────────────────

@app.get("/")
async def root():
    return {
        "service": "AI Translation Agent",
        "version": "2.0.0",
        "status": "running",
        "endpoints": ["/translate", "/transcribe", "/summarize"],
    }


# ── /translate ────────────────────────────────────────────────────

@app.post("/translate", response_model=TranslationResponse)
async def translate(request: TranslationRequest):
    text = request.text.strip()

    if not text:
        raise HTTPException(status_code=400, detail="Text cannot be empty.")

    if len(text) > 5000:
        raise HTTPException(
            status_code=400,
            detail=f"Text too long ({len(text)} chars). Maximum is 5000 characters.",
        )

    # Check cache
    key = _cache_key(text)
    if key in translation_cache:
        return TranslationResponse(translation=translation_cache[key])

    _enforce_rate_limit()

    try:
        chat_completion = client.chat.completions.create(
            model=MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are a professional translator. "
                        "If the text is already in English, respond with exactly: ALREADY_ENGLISH. "
                        "Otherwise, translate the given text to English. "
                        "Only return the translated text, nothing else. No explanations, no notes."
                    ),
                },
                {"role": "user", "content": text},
            ],
            temperature=0.3,
            max_tokens=4096,
        )
        translated_text = chat_completion.choices[0].message.content.strip()
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Groq API error: {exc}")

    if translated_text == "ALREADY_ENGLISH":
        return TranslationResponse(translation="")

    translation_cache[key] = translated_text
    return TranslationResponse(translation=translated_text)


# ── /transcribe ───────────────────────────────────────────────────

@app.post("/transcribe", response_model=TranscribeResponse)
async def transcribe(request: TranscribeRequest):
    """Transcribe base64-encoded audio using Groq Whisper."""

    if not request.audio_data:
        raise HTTPException(status_code=400, detail="No audio data provided.")

    _enforce_rate_limit()

    try:
        # Decode base64 audio to bytes
        audio_bytes = base64.b64decode(request.audio_data)
        print(f"[Transcribe] Received audio: {len(audio_bytes)} bytes, mime: {request.mime_type}")

        # Determine file extension from mime type
        ext = ".webm"
        if "wav" in request.mime_type:
            ext = ".wav"
        elif "mp3" in request.mime_type:
            ext = ".mp3"
        elif "ogg" in request.mime_type:
            ext = ".ogg"

        # Write to a temporary file (Groq SDK requires a file-like object)
        with tempfile.NamedTemporaryFile(suffix=ext, delete=False) as tmp:
            tmp.write(audio_bytes)
            tmp_path = tmp.name

        print(f"[Transcribe] Temp file: {tmp_path} ({os.path.getsize(tmp_path)} bytes)")

        # Call Groq Whisper for transcription
        with open(tmp_path, "rb") as audio_file:
            transcription = client.audio.transcriptions.create(
                model=WHISPER_MODEL,
                file=audio_file,
            )

        # Clean up temp file
        os.unlink(tmp_path)

        # Handle different response formats
        if isinstance(transcription, str):
            result_text = transcription.strip()
        elif hasattr(transcription, 'text'):
            result_text = transcription.text.strip()
        else:
            result_text = str(transcription).strip()

        print(f"[Transcribe] Result: {result_text[:100]}...")
        return TranscribeResponse(text=result_text)

    except Exception as exc:
        import traceback
        traceback.print_exc()
        # Clean up temp file on error
        try:
            os.unlink(tmp_path)
        except Exception:
            pass
        raise HTTPException(status_code=502, detail=f"Transcription error: {exc}")


# ── /summarize ────────────────────────────────────────────────────

@app.post("/summarize", response_model=SummarizeResponse)
async def summarize(request: SummarizeRequest):
    """Translate + summarize transcriptions and optionally email the result."""

    if not request.transcriptions:
        raise HTTPException(status_code=400, detail="No transcriptions provided.")

    # Combine all transcription segments
    full_text = "\n\n".join(request.transcriptions)

    if not full_text.strip():
        raise HTTPException(status_code=400, detail="Transcriptions are empty.")

    _enforce_rate_limit()

    # Call Groq LLM to translate + summarize
    try:
        chat_completion = client.chat.completions.create(
            model=MODEL,
            messages=[
                {
                    "role": "system",
                    "content": (
                        "You are an expert translator and summarizer. "
                        "You will receive transcribed text from a video. "
                        "The text may be in any language. Your task:\n"
                        "1. If the text is not in English, translate it to English.\n"
                        "2. Create a clear, well-structured summary of the content.\n"
                        "3. Include key points, main topics discussed, and any important details.\n"
                        "4. Format the summary with sections if the content covers multiple topics.\n"
                        "5. Keep the summary concise but comprehensive.\n\n"
                        "Return ONLY the summary, no meta-commentary."
                    ),
                },
                {"role": "user", "content": full_text},
            ],
            temperature=0.3,
            max_tokens=4096,
        )
        summary = chat_completion.choices[0].message.content.strip()
    except Exception as exc:
        raise HTTPException(status_code=502, detail=f"Summarization error: {exc}")

    # Send email
    email_sent = False
    if request.email:
        email_sent = _send_email(
            to_email=request.email,
            subject="🌐 AI Translation Agent — Video Summary",
            body=summary,
        )

    return SummarizeResponse(summary=summary, email_sent=email_sent)
